config/routes.rb
MK1::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
root :to => 'paginas#home'
## ADMIN
  get '/admin' => 'admin#admin', :as => 'admin'
  get '/admin/foto/:id/:type' => 'admin#foto', :as => 'admin_foto'
  get '/manual', :to => 'admin#manual_update', :as => 'manual'
  get '/aprobadas' , :to => 'admin#aprovado', :as => 'aprovado'
  get '/borrar', :to => 'admin#delete', :as => 'borrar'
  #Paginas
  get '/show/:id', :to => 'paginas#show', :as => 'show'
  post '/show/:id/comment', :to => 'paginas#comment', :as => 'comment_pagina'
  post '/show/:id/ranking', :to => 'paginas#ranking', :as => 'ranking_pagina'
  get '/visit/', :to => 'paginas#visit', :as => 'visit' 
  
end

app/models/categorie.rb
class Categorie < ActiveRecord::Base
	attr_accessible :categoria
  	acts_as_nested_set
end

app/models/mk1.rb
class Mk1 < ActiveRecord::Base
  paginates_per 5
  attr_accessible :instagram_id, :instagram_link, :pic_large, :pic_med, :pic_thumb, :username, :publicado, :fullname, :visit,:tag_list
  acts_as_taggable
  def to_param
    "#{id}-#{username}"
  end
  def increment(by = 1)
    self.visit ||= 0
    self.visit += by
    self.save
  end
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  attr_accessible :post_id, :usuario_id, :raiting
  has_one :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :provider, :uid, :name, :email, :password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end
    end
  end
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.info.name,
          provider:auth.provider,
          uid:auth.uid,
          email:auth.uid+"@twitter.com",
          password:Devise.friendly_token[0,20],
        )
      end
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def admin
     @fotos = Mk1.where(:publicado => false).order('created_at DESC').all
  end
  def foto
    type = params[:type]
    id = params[:id]
    foto = Mk1.find(id)
    if type == "1"
      foto.publicado = true
    elsif type == "0"
      foto.publicado = false
    end
    if foto.save
      redirect_to admin_path
    end
  end
  def manual_update
    Instagram.tag_recent_media("gti").each do |dato|
      foto = Mk1.find_or_create_by_instagram_id(
        :instagram_id => dato.id,
        :instagram_link => dato.link,
        :pic_thumb => dato.images.thumbnail.url,
        :pic_med => dato.images.low_resolution.url,
        :pic_large => dato.images.standard_resolution.url,
        :fullname => dato.user.full_name,
        :username => dato.user.username
      )
      foto.save
    end
    redirect_to admin_path
  end
  def delete
    Mk1.where(:publicado => false).delete_all
    redirect_to admin_path 
  end
  def aprovado
    @fotos = Mk1.where(:publicado => true).order('created_at DESC').page(params[:page]).per(12)
  end
  private
  def authenticate
    authenticate_or_request_with_http_basic do |user, password| 
        session[:admin]= (user == ENV['username'] && password == ENV['password'])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def home
    @fotos = Mk1.where(:publicado => true).order('created_at DESC').page(params[:page]).per(10)
  end

  def new_stuff
    Instagram.process_subscription(request.body.read) do |handler|
      handler.on_tag_changed do |tag, data|
        @inst = Instagram.tag_recent_media("gti");
        @inst.each do |data|
          mkfoto = Mk1.find_or_create_by_instagram_id(
            :instagram_id => data.id,
            :instagram_link => data.link,
            :pic_thumb => data.images.thumbnail.url,
            :pic_med => data.images.low_resolution.url,
            :pic_large => data.images.standard_resolution.url,
            :fullname => data.user.full_name,
            :username => data.user.username
          )
          mkfoto.save
        end
      end
    end
    render :text => ""
  end
  def show
    @fotos = Mk1.find params[:id]
    @comment = Comment.new
    @comments = Comment.where(:commentable_id => @fotos).order('created_at DESC')
    @ranking = Ranking.new
    @fotos.increment
  end
  def comment
    @mk1 = Mk1.find params[:id]
    @comment = @mk1.comments.new params_comment
    @comment.user_id =  current_user.id
    if @comment.save
      redirect_to show_path(params[:id])
    else
      render :show
    end
  end
  def ranking
    @ranking = Ranking.new
    @ranking.raiting = params[:commit].to_i.inspect
    @ranking.post_id = params[:id]
    if @ranking.save
      redirect_to show_path(params[:id])
    else
      render :show
    end
  end
  def visit
    @visit =Mk1.order("visit DESC").last(5)
  end
  def params_comment
    params.require(:comment).permit(:comment, :title)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def twitter
    auth = env["omniauth.auth"]
    #Rails.logger.info("auth is **************** #{auth.to_yaml}")
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/admin/admin.html.haml
%ul
  - @fotos.each do |foto|
    %li
      = image_tag foto.pic_thumb, :width => 250, :height => 250
      - if foto.publicado
        .aprobado
          %a.icon{:href => admin_foto_path(foto.id, 0)}
      - else
        .desaprobado
          %a.icon{:href => admin_foto_path(foto.id, 1)}

app/views/admin/aprovado.html.haml
%ul
  - @fotos.each do |foto|
    %li
      = image_tag foto.pic_thumb, :width => 250, :height => 250
      - if foto.publicado
        .aprobado
          %a.icon{:href => admin_foto_path(foto.id, 0)}
      - else
        .desaprobado
          %a.icon{:href => admin_foto_path(foto.id, 1)}
= paginate @fotos 

app/views/comment/_comments.html.haml
= form_for @comment, :url => comment_pagina_path do |f|
  %ul
    %li.picture
      = image_tag"home/noavatar.png"
    %li.comments
      %p
        = f.text_area :comment, :placeholder => "It leaves your comment"
  %p.comment
    =f.submit "Comment", :class => "btn btn-primary"

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:charset => "UTF-8"}
    %title MK1
    %meta{:content => "#MK1", :property => "og:title"}
    %link{ :rel => "shortcut icon", :href => "/favicon.ico", :type => "image/x-icon"}
    %meta{:name => "description", :content => "#MK1. ómale una foto a tu volkswagen en instagram y lucete ante la demas gente."}
    %meta{:content => "#MK1. Tómale una foto a tu volkswagen en instagram y lucete ante la demas gente.", :property => "og:description"}
    %meta{:content => "http://vwmk1.mx", :property => "og:url"}
    %meta{:content => "#MK1", :property => "og:site_name"}
    %meta{:content => '/social.jpg', :property => "og:image"}
    %meta{:content => "IE=Edge", "http-equiv" => "X-UA-Compatible"}
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
  %body
    #mk1
      #admin
        %ul#menu
          %li=link_to "Home", root_path
          %li=link_to "Actualizar manualmente", manual_path
          %li= link_to "Borrar no Aprobados ",borrar_path
          %li
            %a{:href => '#'}
              Total de fotos:
              = "#{Mk1.where(:publicado => true).count}/#{Mk1.count}"
          %li= link_to "Aprobadas",aprovado_path
        .cuerpo
          = yield
    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!! 5
:plain
  <!--[if lt IE 7]> <html lang="es" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
  <!--[if IE 7]>    <html lang="es" class="no-js lt-ie9 lt-ie8"> <![endif]-->
  <!--[if IE 8]>    <html lang="es" class="no-js lt-ie9"> <![endif]-->
  <!--[if gt IE 8]><!--> <html lang="es" class="no-js"> <!--<![endif]-->
%head
  %meta{:charset => "UTF-8"}
  - if current_page?('/')
    %title Volkswagen GTI
    %meta{:content => "Volkswagen GTI", :property => "og:title"}
    %meta{:name => "robots", :content => "noindex"}
  -else
    %title
      #{"#{yield(:titulo)} | " if content_for?(:titulo)} #VolksGTI
    %meta{:content => "#{yield(:titulo)} | Volkswagen GTI", :property => "og:title"}
  %link{ :rel => "shortcut icon", :href => "/favicon.ico", :type => "image/x-icon"}/
  %meta{:name => "description", :content => yield(:descripcion)}
  %meta{:content => yield(:url), :property => "og:url"}
  %meta{:content => "Volkswagen GTI", :property => "og:site_name"}
  %meta{:content => yield(:imagen), :property => "og:image"}
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
  %body
    .row
      .header
        %ul.nav.nav-tab
          %li
            = link_to "GTI", root_path
          %li
            = link_to "Home", root_path
          %li
            = link_to "It Takes Part","#"
          %li
            = link_to "More Visit", visit_path
          %li 
            - if current_user.nil?
              %p= link_to "Sign up", new_user_registration_path
              %p= link_to "Sign in", user_session_path
            - else
              %p= link_to "Sign out", destroy_user_session_path, :method => :delete
    .content
      .row
        .col-md-8
          = yield
        .col-md-4
      .footer
    :plain
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-8596932-3', 'volksgti.com');
        ga('send', 'pageview');
      </script>
    = javascript_include_tag "application"

app/views/paginas/_galeria.html.haml
.vista{:pagina => "inicio"} 
  %ul
    - @fotos.each do |foto|
      %li.thumb
        %h1.name= link_to "Picture by: @#{foto.username}", show_path(foto), :target => 'blank'
        .sombra

        = link_to image_tag(foto.pic_large, :width => "90%", :height => "90%"),show_path(foto), :"data-id" => foto.instagram_id
        %p= "Date: "+foto.created_at.to_date.to_s

app/views/paginas/home.html.haml
= render 'galeria'
= paginate @fotos 

app/views/paginas/show.html.haml
- provide :titulo, @fotos.username 
- provide :url, "http://mk1.herokuapp.com/#{@fotos.id}"+"-"+"#{@fotos.username}"
- provide :imagen, @fotos.pic_large
//- provide :descripcion, @producto.descripcion.html_safe[0..160]
#ver{:vista=>"show"}
  %ul
    %li 
      = link_to image_tag(@fotos.pic_large, :width => 640, :height => 640),@fotos.instagram_link, :target => 'blank', :"data-id" => @fotos.instagram_id
      %h2
        = link_to "Picture by: @#{@fotos.username}", @fotos.instagram_link, :target => 'blank'
    %li.social
      %h2  Share with all your friends: 
      .fb-like{"data-action" => "like", "data-href" => "http://mk1.herokuapp.com/#{@fotos.id}"+"-"+"#{@fotos.username}", "data-layout" => "button_count", "data-share" => "true", "data-show-faces" => "true"}
      #fb-root
        :plain
          <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=183182198556809";
            fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
          </script>
      %a.twitter-share-button{"data-hashtags" => "Gti", "data-url" => "http://http://mk1.herokuapp.com/\#{@fotos.id}&quot;+&quot;-&quot;+&quot;\#{@fotos.username}", :href => "https://twitter.com/share"} Tweet
  .ranking
    %p Ranking
    = render'votes/ranking'
  #disqus_thread
  :javascript
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'volksgti'; 
    // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
:plain
  <script>
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  </script>

app/views/paginas/visit.html.haml
.vista{:pagina => "visitas"} 
  %ul
    - @visit.each do |foto|
      - stats = stats(foto.id);
      %li.thumb
        %h1.name= link_to "Picture by: @#{foto.username}", foto.instagram_link, :target => 'blank'
        .sombra

        = link_to image_tag(foto.pic_large, :width => "90%", :height => "90%"),show_path(foto), :"data-id" => foto.instagram_id
        %p= "Date: "+foto.created_at.to_date.to_s
        %p= "Comments "+ stats.comments.count.to_s

app/views/votes/_ranking.html.haml
= form_for @ranking, :class=>"ranking_form", :url => ranking_pagina_path do |f|
  .div_gauge
  =f.submit "1", :raiting => 1, :class=>"btn-estrella"
  =f.submit "2", :raiting => 2, :class=>"btn-estrella"
  =f.submit "3", :raiting => 3, :class=>"btn-estrella"
  =f.submit "4", :raiting => 4, :class=>"btn-estrella"
  =f.submit "5", :raiting => 5, :class=>"btn-estrella"